### ISSUE TITLE
Help me (not really an issue, lol)

### ISSUE THREAD

**Issue by xtc-dev** [QuiteAFancyEmerald/InvisiProxy#14]
Hey Emerald, I want to improve Vented by adding some more features that may be in Holy Unblocker, so if you could help me better understand and implement these, I'd appreciate it. 

> How do you add a custom tab cloak (like in the options tab)
> May I implement some of the same games you have, and can you tell me how?
> I want to implement VMs also

(both my alt and my main discord account have been disabled, so if you can find another way to contact me, that'd be great!)

**Comment by QuiteAFancyEmerald** [comment]
The particular script in use for the Tab Cloak menu is located at
'/assets/js/header.js.' Just make sure you implement the correct id
attributes in order for the script to work. Also note that this is cookie
based.

I'll list out some of the values of the ids used within the script: "csel"
(the entire menu), "titleform" and lastly "iconform." All of which use the
$ function.

Regarding the addition of any games you would like implemented from Holy
Unblocker, simply cloning the repo and hosting the assets locally should
work. Same goes for hosting something like vibeOS. If you are trying to set
up an in-browser environment, be sure to look at all of the given
documentation provided from the creators.

Apologies for any typos since I am currently just speeding an email for
this. :)

**Comment by xtc-dev** [comment]
Thank you, I will use this!
