### ISSUE TITLE
Where do I get more Holy Unblocker sites?

### ISSUE THREAD

**Issue by ghost** [QuiteAFancyEmerald/InvisiProxy#44]
Can i get a site plz cuz my school legit just blocked a site i got 1 day after i got it

**Comment by QuiteAFancyEmerald** [comment]
**How do I obtain more Holy Unblocker sites that are not blocked by my school district or administration?**
If you join the TN discord, you can click on the button in #panel (make sure you verify first!) and the bot in the server will DM you another site. Sites are restocked on a monthly basis and you are limited to 3-9 sites per month, depending on if you are boosting the server or donating.

TN Discord (old): https://discord.gg/hcUUceSCtj
New Invite: https://discord.gg/CwWpdGkuWY
Official Invite: https://discord.gg/unblock

**More information:**
This issue has now been pinned due to the number of users asking for more mirrors due to these "reasons":

1) "I don't have another device or Discord"
2) "I can't access Discord"
3) "I would rather not join the Discord or have some other odd reason"

**If you follow any of the criteria above, sorry. I can't do anything about it. Consider self-hosting. Please do not ask for more sites or spam issues.**

**Exception:** "The sites I got from the proxy bot were blocked for my filter." Create a ticket in the discord about this. You sometimes obtain sites from the proxy bot meant for other filters. By sending me a screenshot (proof of it being blocked) I'll provide you with another Holy Unblocker site for your particular filter.  

Lastly (sad that I need to define this) a filter is what your district, school, or workplace uses to block sites. People often call them "blockers" here.

**Comment by Floisasimp** [comment]
I cant verify my discord dont have a phone what do i do

**Comment by QuiteAFancyEmerald** [comment]
I can give you the phoneless role. What is your Discord tag?

**Comment by Floisasimp** [comment]
I cant verify my discord so i cant access it it shows the page where u have to type in ur phone number but i dont have a phone so i cant do it i need

**Comment by QuiteAFancyEmerald** [comment]
Oh, rip. Well, here is a site you can use: https://grammarfiles.net

Closing this for now.
